export const meta = {
  name: 'aetherfall-wave1b',
  description: 'Wave 1b: critic-first on the already-built pieces (HUD builds first), fix loop until WIN or rounds exhausted',
  phases: [
    { title: 'Build', detail: 'one builder per piece, owns its files only' },
    { title: 'Critique', detail: 'fresh critic inspects the running game, blind A/B vs real game' },
    { title: 'Fix', detail: 'builder round N with critic gaps' },
  ],
}

const CRITIC_SCHEMA = {
  type: 'object',
  properties: {
    piece: { type: 'string' }, verdict: { type: 'string', enum: ['WIN', 'TOSSUP', 'LOSE'] }, score: { type: 'number' },
    scores: { type: 'object', properties: { visual: { type: 'number' }, feel: { type: 'number' }, performance: { type: 'number' }, polish: { type: 'number' } } },
    biggest_gap: { type: 'string' }, gaps_ranked: { type: 'array', items: { type: 'string' } }, strengths: { type: 'array', items: { type: 'string' } },
    evidence: { type: 'array', items: { type: 'string' } }, errors: { type: 'array', items: { type: 'string' } },
    perf: { type: 'object', properties: { fps: { type: 'number' }, p95ms: { type: 'number' }, p99ms: { type: 'number' }, calls: { type: 'number' }, tris: { type: 'number' } } },
  },
  required: ['piece', 'verdict', 'score', 'biggest_gap', 'gaps_ranked', 'evidence'],
}

const COMMON = `Project: C:\\Users\\ianca\\Desktop\\FPS3 (browser FPS-RPG "Aetherfall", Three.js). FIRST read CLAUDE.md and tools/BUILDER.md in full and follow them exactly. Dev server already runs at http://127.0.0.1:5173/. Work autonomously, no questions. Use the harness to look at your actual result and iterate until it meets the bar; don't stop at "it runs".`

const PIECES = [
  { key: 'sky', files: 'src/render/Sky.js', brief: `PIECE: Sky / atmosphere / time of day (FF14-grade skies). Own: src/render/Sky.js only. Contract = its header doc. Deliver: a sky dome shader with physically-inspired Rayleigh/Mie scattering (sun glow, horizon warmth, zenith deep blue), a bright sun disc with glare (expose sky.sunMesh for god rays), a moon + star field + subtle aurora/aether ribbons at night, layered procedural clouds (2 layers, noise-based with lit edges, silver lining toward the sun, slow drift, dramatic towering feel at golden hour — these must NOT look like flat noise blobs), horizon haze, and a full 24h cycle driving sunDir/sunColor/skyColor/horizonColor/fogColor/ambientColor/groundColor/fogDensity/sunIntensity/night so Lighting/Water/Grass read consistent values. Keep scene.fog (FogExp2) synced to fogColor/density. Dawn (6), noon (13), golden hour (17.5), dusk (19), night (23) must each be a painting. The sky must follow the camera (no parallax) and cost ≤ 0.4 ms. Check all 5 times of day in screenshots at 1080p; compare against FF14 La Noscea / Destiny EDZ skies in your mind and push until it would hold up.` },
  { key: 'lighting', files: 'src/render/Lighting.js', brief: `PIECE: Lighting & shadows. Own: src/render/Lighting.js only. Deliver: sun DirectionalLight driven by game.sky (dir/color/intensity incl. night moonlight with cool tint), cascaded shadow maps (use three/addons/csm/CSM.js or your own 2-3 cascades) that are soft (PCF/PCSS-like), stable (no swimming/shimmer when moving — texel snapping), tight near the player (crisp self-shadows on props/grass/enemies within 30m) and fading out at distance; hemisphere/ambient from sky.ambientColor/groundColor; an environment map for specular/diffuse IBL built procedurally from the sky colors (PMREM of a tiny gradient scene, regenerated when the hour changes noticeably — cheap) set on scene.environment; shadow camera follows the player. Make sure MeshStandardMaterial world surfaces (terrain, props, enemies) receive good-looking light: golden hour rim, blue-ish shadows at noon, moonlit night that is still readable. If you use CSM note that custom ShaderMaterials won't receive CSM shadows; document clearly in your report how other builders make materials CSM-compatible (e.g. CSM.setupMaterial). Budget 0.8 ms. Verify with screenshots at several hours and with the perf window.` },
  { key: 'postfx', files: 'src/render/PostFX.js', brief: `PIECE: Post-processing pipeline. Own: src/render/PostFX.js only (keep setOverlay/ClearPass overlay behaviour intact — weapons renders the first-person gun through it). Deliver using the installed 'postprocessing' lib: HDR half-float pipeline; bloom tuned for a soft FF14 glow (not blown out); SSAO/GTAO-ish ambient occlusion (postprocessing SSAOEffect with normal pass, or N8AO-style in-house; must be subtle and stable); god rays from game.sky.sunMesh (GodRaysEffect) that look great at golden hour and are off when sun is below horizon; a color grade (procedural 3D LUT or curves: lifted soft shadows slightly cool, warm highlights, gentle saturation boost, filmic contrast) — FF14 painterly; vignette; subtle film grain; chromatic aberration only on hits (kick()); flash(color,strength,duration) full-screen tint; optional depth-of-field for ADS (setDof) that is cheap; anti-aliasing: SMAA high preset (clean edges, no shimmer on grass/foliage); ACES or AgX tone mapping with exposure that adapts to time of day (read game.sky). Quality presets: q=low disables AO/godrays/DoF. Budget 1.3 ms at 1080p. Prove it with screenshots (noon, golden hour, night) and perf windows; every effect must be visible in at least one shot. Also export small hooks other systems can call: postfx.flash, postfx.kick, postfx.setDof, postfx.exposure.` },
  { key: 'terrain', files: 'src/world/Terrain.js', brief: `PIECE: Terrain. Own: src/world/Terrain.js only. Keep the API (size, waterLevel, heightAt, normalAt, slopeAt, mesh). Deliver: a heightfield with real LOD (clipmap/quadtree or concentric rings: ~0.5-1 m resolution near the player, coarse far away; no visible cracks/popping; follows the player), shaped to the World layout in CLAUDE.md (spawn meadow flat-ish, Mirrormere lake basin below waterLevel with beaches + island, Sundered Spire plateau, Whisperwood rolling ground, crystal fields, flat boss arena, mountain ring with cliffs + a pass vista), with a triplanar procedural material (MeshStandardMaterial + onBeforeCompile) blending grass / dirt / rock / sand / snow by slope+height+noise, macro-variation to kill tiling, detail normal/bump from noise, wetness darkening at the shoreline, cliffs with strata. Procedural textures via canvas/DataTexture with mipmaps + anisotropy. Must receive shadows. Budget 0.8 ms, ≤ 40 draw calls. heightAt must be analytic (no mesh lookup) and stay cheap (grass samples it 100k+ times at init). Also expose terrain.biomeAt(x,z) -> 'meadow'|'forest'|'lake'|'ruins'|'crystal'|'arena'|'mountain' and terrain.POI = {spawn, waystone, lake, ruins, forest, crystal, arena} Vector3s at ground height. Verify ground-close shots (texture quality underfoot), vistas, the lake basin, cliffs.` },
  { key: 'water', files: 'src/world/Water.js', brief: `PIECE: Water (reference: threejswaterpro.com quality). Own: src/world/Water.js only. Deliver: a lake surface at terrain.waterLevel wherever terrain < waterLevel (at least Mirrormere; a large plane with height-based clipping or a mesh covering the basin) with: planar reflections (real, of sky+terrain+props, rendered at reduced res with a clip plane), refraction with depth-based color absorption (turquoise shallows → deep blue), shoreline foam and soft depth edge (needs scene depth: render a depth texture or compute from terrain.heightAt per-vertex/pixel), Gerstner/sum-of-sines waves + animated normal detail, sun specular glitter following game.sky.sunDir/sunColor, Fresnel, caustics-like light dapple on the lake bed (optional, cheap), fog-respecting. Must look stunning at golden hour and at night (moon reflection). Budget 0.8 ms incl. reflection pass (reflection at 0.5x res, skip in q=low). Expose water.level, water.isWater(x,z), water.heightAt(x,z) (wave displacement, for splashes) and water.submergedDepth(pos). Verify from the shore of Mirrormere at several angles/times (teleport to about (-95, null, -50) looking toward (-170,-70)).` },
  { key: 'grass', files: 'src/world/Grass.js', brief: `PIECE: Grass (reference: aleksandargjoreski.dev/blog/trimming-my-grass-shader — instanced blades, cheap vertex wind, LOD). Own: src/world/Grass.js only. Deliver: dense instanced grass blades (InstancedBufferGeometry, 3-5 verts per blade, curved, tip thinning) around the player in a moving grid of chunks/tiles, density falling off with distance + fading to terrain color (no hard cutoff, no popping), placed only where terrain.biomeAt/slope allows and above waterLevel, height/color varied by noise and terrain color, wind (gusts via noise, blade bending), player interaction (blades bend away from the player + trail), subtle specular/translucency, shadows received (cheap) and cast only near. FF14 Shroud / Destiny Nessus field density is the bar — the meadow must look lush, not sparse. Also flowers/wild herbs scattered (same system, different blade shape/color) and glowing aether motes near crystals optional. Budget 1.0 ms at q=high, scale count by quality. Zero per-frame allocation. Verify ground-close shot, walk-through bursts (bending), vista (fade), perf idle+sprint windows.` },
  { key: 'vegetation', files: 'src/world/Vegetation.js, src/world/Props.js (and additive helpers in src/world/Colliders.js)', brief: `PIECE: Vegetation + props/landmarks. Own: src/world/Vegetation.js, src/world/Props.js (Colliders.js additive only). Deliver procedurally: (a) trees — at least 3 species (tall FF14-style slender trunks with layered leaf canopies, a gnarled old tree, a willow-ish lake tree) via InstancedMesh with LOD (billboard/impostor far), trunk bark material, leaf cards with alpha cutout + wind sway + translucency, placed by biome (Whisperwood dense, scattered elsewhere); (b) rocks/boulders (3-4 shapes, triplanar rock material) ; (c) glowing aether crystals (clusters, emissive blue-violet, bloom-friendly, subtle pulse) esp. crystal fields; (d) Props.js landmarks: the Waystone at (0,-28) (a huge faceted floating crystal slowly rotating above an ornate stone plinth with rune glyph rings), Sundered Spire ruins (broken columns, arches, cracked tower, stairs) at (140,60), monolith ring at the boss arena (-60,260), some scattered standing stones + lanterns near the spawn path, glowing mushrooms in the forest. Everything registers colliders (game.world.colliders.add) so the player can't walk through trunks/rocks/pillars. Cast/receive shadows near. Budget 0.8 ms, ≤ 60 draw calls (instancing!). Verify spawn-looking-at-waystone shot (look: [3.14, 0.1] from origin looks toward -z? compute: yaw 0 looks toward -Z), forest shots (teleport (0,null,-230)), ruins (teleport (100,null,60) look toward them), crystal field, and collision (walk into a tree in a step script; state.pos must stop).` },
  { key: 'movement', files: 'src/player/PlayerController.js', brief: `PIECE: Movement controller — Destiny 2 Hunter feel. Own: src/player/PlayerController.js only (Player.js/PlayerCamera.js are others'). Deliver: tuned walk 6.5 / sprint ~10 m/s with acceleration curves (quick start, slight weight), sprint requires forward-ish input, sprint cancels on fire/ADS (expose flags others can set: controller.sprintBlocked), crouch, slide (momentum boost, duration, on slope speeds up, cancels into jump keeping speed — Destiny slide-jump), double jump (Destiny: second jump with directional boost + a short 'glide' if held? implement double jump + brief float when holding Space on 2nd jump), air control, coyote time, jump buffering, landing (impact value by fall speed, brief speed reduction on hard landings), ledge forgiveness, ground snapping on downhill so you don't hop, stairs/steps up to 0.6 m climb (colliders box tops), slopes > 50° slide down, water: wading slowdown if game.world.water?.submergedDepth says submerged, swimming if deep; footstep events 'player:footstep' {surface, speed} cadenced by speed; everything frame-rate independent (test with dt variations). Expose state fields the HUD/camera/weapons read (state, speed, grounded, sliding, crouched, velocity, wishDir, sprintBlocked). Verify with step scripts: record state.pos/speed over time (use eval loops) to confirm accel/decel timing (walk reaches 95% in ~0.2 s, stop in ~0.15 s), slide distance ~8-10 m, double jump height, no falling through terrain at high speed, no jitter on slopes (burst shots while walking downhill), stable on colliders.` },
  { key: 'camera', files: 'src/player/PlayerCamera.js', brief: `PIECE: Camera feel — Destiny 2 first person. Own: src/player/PlayerCamera.js only. Deliver: mouse look with proper sensitivity (exposed, default ~ Destiny 'sens 5' at 800dpi feel), pitch clamp, FOV base 95-100 with sprint kick (+8), slide kick, ADS zoom blend per weapon (read game.player.weapons.current?.zoom if present, else 1.3x) with fast in (0.18 s) / slightly slower out, head bob that is subtle and speed-scaled (vertical figure-8, lateral sway, reduced when ADS), landing dip with spring (impact-scaled), slide camera lowering + slight roll, strafe roll, crouch height blend, trauma-based camera shake (shake(strength) adds trauma; shake = trauma², decays; perlin-ish not random jitter), recoil kick with smooth recovery (kick(pitch,yaw) with recoil accumulating while firing and recovering after), damage flinch hook (flinch()), idle breathing sway, jump apex float feel (tiny fov/pos), smooth eye height transitions. Expose: eye, yaw, pitch, fov, ads, look(), setAds(), kick(), shake(), flinch(), sensitivity, plus per-frame offsets weapons can read for viewmodel sway: view.sway = {x,y} (look-lag), view.bobOffset (Vector3). Verify: burst sequences while walking/sprinting (bob visible but subtle), a shake+kick via eval, ADS shot, landing.` },
  { key: 'weapons', files: 'src/player/Weapons.js and new files under src/player/weapons/', brief: `PIECE: Weapons + first-person viewmodel — Destiny 2 bar. Own: src/player/Weapons.js + src/player/weapons/*.js. Contract in Weapons.js header. Deliver: 6 archetypes with distinct stats and feel (handcannon, autorifle, pulse, shotgun, sniper, fusion) + 3 equipped slots (kinetic HC, energy AR (arc), power sniper (solar) by default; the others reachable via weapons.give(id, slot) for testing). Procedural gun models that look like real sci-fantasy guns (strong silhouettes from boxes/cylinders/lathes, beveled edges via geometry tricks, dark metal + brass/gold FF14 filigree + glowing element accents, emissive sights), rendered in the overlay scene via game.postfx.setOverlay(vmScene, vmCam) with your own lights (mirror sky sun) — NEVER clipping. Procedural animation state machine: idle sway/breath, walk/sprint bob (read controller), sprint pose (gun lowered, tilted), ADS blend (gun to center, sights aligned to crosshair; fov via view.setAds), fire recoil (kick back+up + rotational, per-archetype), reload (drop/tilt, magazine out/in motion with visible moving part, duration per archetype), swap (lower/raise, ~0.4 s), landing dip, look-lag sway (read view.sway). Firing: rpm-accurate timing, hitscan via game.combat.hitscan (fusion/sniper fine too), spread/bloom for hipfire, per-archetype recoil pattern applied via view.kick, ammo/reserve/reload logic, empty click, auto-reload on empty when firing, muzzle flash mesh (quad/cross emissive, 1-2 frames) at the muzzle + vfx.emit('muzzle') + vfx.tracer + vfx.flash, audio.play('shot-<archetype>'), events 'weapon:fire' etc. Keys: LMB, RMB ADS (toggle-hold), R, 1/2/3, wheel. Budget 0.3 ms. Verify with shots: idle, sprint, ADS, firing burst (muzzle flash visible), reload mid-animation, each weapon swapped (eval weapons.swap(1) etc.). The gun should look like it belongs in Destiny, not a grey box.` },
  { key: 'abilities', files: 'src/player/Abilities.js', brief: `PIECE: Abilities (Destiny kit). Own: src/player/Abilities.js only. Deliver the minimum kit from the header (grenade lob with arc + bounce + explode (combat.explode + vfx), melee lunge+shockwave with small dash, heal rift sigil on the ground (glowing ring mesh + heals player inside), super 'Starfall' 6 s: fast homing bolts (combat.projectile with homing to nearest enemy) + strong vfx + postfx flash/kick on activation) with cooldowns (grenade 25 s, melee 15 s, class 40 s, super meter fills via 'combat:hit' damage events and passively), key handling (G/F/Q/X), super cannot fire weapons (set controller/weapons flags defensively), events 'ability:use'/'ability:ready'. Build visible meshes for the grenade (glowing orb) and rift (ornate FF14-style sigil ring on terrain). Expose abilities.list in the contract shape + abilities.charge(id) for tests + abilities.superMeter. Verify by eval: use each ability and screenshot the effect.` },
  { key: 'combat', files: 'src/combat/Combat.js', brief: `PIECE: Combat / damage resolution. Own: src/combat/Combat.js only. Implement the full header contract: registry, hitscan (targets capsule/sphere + weakPoints with mult, world colliders, terrain ray-march; return object always), projectiles (pooled, visual mesh/sprite with emissive color per element + optional trail via vfx.attach, gravity, homing, explode on hit, life), explode with falloff + knockback, direct damage, targetsInRadius, nearest, rayWorld; crit determination; damage falloff hook (pass range + falloffStart); elemental shield rules (shield of matching element takes 2x, wrong element normal — simple Destiny 'match game' feel: targets may have shieldElement); emits all events; kill handling (target.alive false, 'combat:kill'); player-team vs enemy-team filtering; zero per-frame allocation. Also add a tiny debug helper combat.spawnDummy(pos) that registers a static target (so weapons/vfx/hud can be tested before enemies exist) with a visible capsule mesh + health that regenerates after death for testing — expose on combat. Verify by eval: spawnDummy in front of spawn, fire, check report/console that 'combat:hit' fires (subscribe via eval and count) and dummy health decreases; projectiles travel/explode; terrain impacts return surface 'terrain'.` },
  { key: 'enemies', files: 'src/enemies/Enemies.js and new files under src/enemies/', brief: `PIECE: Enemies — procedural creatures + AI (reference github.com/Ariescar/anyCreature idea: procedurally assembled creatures with procedural gait). Own: src/enemies/Enemies.js + src/enemies/*.js. Deliver the 6 types in the header with distinct procedural bodies (wisp: floating glowing core with orbiting shards + trail; hound: quadruped with procedural 4-leg gait, head tracking, tail; sentinel: tall biped with spear/orb, shield bubble; golem: heavy rock body with glowing crystal core weak point, slam; drake: winged flyer with flapping, dives; warden: large mini-boss) using shared geometries + per-instance color/emissive, FF14-mystical materials (stone, aether glow, shells), idle/chase/attack/stagger/death animations (procedural: bones as Object3D hierarchy with sine/IK-ish stepping; death = collapse + dissolve via material opacity/scale + vfx.emit('death')), AI state machines (perception radius, LOS via combat.rayWorld, steering on terrain with heightAt + slope + collider avoidance, flocking for packs, strafing for ranged, retreat when hurt for wisps), attacks (ranged: combat.projectile team 'enemy' with telegraph glow; melee: combat.damage on player target with wind-up; golem slam: combat.explode), health/shield scaling by level, stagger on heavy hits, head/weakpoint crits (register weakPoints), populate() placing camps per World layout (ruins, forest edge, crystal fields; few wisps near spawn), respawn timers, bounded alive count (≤ 40) with update LOD by distance (far enemies tick at lower rate), nameplate data (name, level) for HUD. Events per contract. Budget 0.6 ms for ~30 enemies. Verify: eval game.enemies.spawn('hound', pos) x3 near the player and screenshot bursts (gait), spawn each type for a lineup shot, confirm they chase/attack (player hp drops in state), kill one via combat.damage and screenshot death.` },
  { key: 'vfx', files: 'src/vfx/VFX.js and new files under src/vfx/', brief: `PIECE: VFX. Own: src/vfx/VFX.js + src/vfx/*.js. Implement the header contract: an instanced/GPU particle system (one InstancedMesh or Points-with-attributes per blend mode: additive + alpha; per-particle pos/vel/life/size/color/rotation/gravity/drag updated on CPU in typed arrays (pool ~20k) or on GPU via simulated attributes; soft additive textures generated on canvas: spark, glow, smoke puff, ring, star, rune), presets listed in the contract with real art direction (muzzle: bright core + sparks + a little smoke; impact-terrain: dust puff + dirt bits; impact-rock: sparks + chips; impact-enemy: aether sparks in element color + small ring; explosion: flash + fireball puff + shockwave ring + embers + dust; aether-burst: spiral motes; death: rising motes + ring; sigil: rotating rune ring mesh), tracers (instanced thin stretched quads/lines with glow, fast fade), beams, decals (InstancedMesh quads projected onto surface normal, pooled 200), light flashes (pooled PointLights, max 4), attach() emitters following objects (trails/auras), shockwave rings. Subscribe to the combat/player events listed. Element colors from ELEMENT_COLORS. Zero per-frame allocation; ≤ 8 draw calls for all particles; budget 0.4 ms with 5k live particles. Verify by eval: call each preset in front of the camera and screenshot (burst sequences to see lifetime), plus fire the dummy path if combat exists.` },
  { key: 'audio', files: 'src/audio/Audio.js and new files under src/audio/', brief: `PIECE: Audio (all synthesized). Own: src/audio/Audio.js + src/audio/*.js. Implement the header contract with WebAudio: a master bus with compressor/limiter + reverb send (procedural impulse), 3D panning (PannerNode HRTF or equalpower with distance rolloff) for positional sounds, pooled voices, each SFX name synthesized with care (gunshots: layered noise burst through bandpass sweep + low thump + click transient + short tail per archetype; sniper adds echo; fusion charge = rising whine; reload = mechanical clicks sequence; footsteps = filtered noise taps per surface; impacts; hits (short tick), crit (brighter tick), kill (chime); abilities (whooshes/sparkles); UI ticks; explosion = boom + debris), ambient bed (wind noise shaped by filter LFOs, birds/insects chirps via short FM blips by time of day, night crickets), music: generative mystical pad (detuned saws through lowpass + slow chords in dorian/lydian, soft arpeggio, very FF14-field-music) with low volume, started after first gesture. Listens to game events per contract so most sounds happen automatically. Unlock on first click/keydown; silent in game.auto but state tracked (expose audio.debugLastPlayed list so harness can verify triggers). Expose setMaster/music/ambient. Verify via eval in the harness: audio.debugLastPlayed populates on firing etc.; also create a tiny offline-render self-check (OfflineAudioContext) that renders 'shot-handcannon' and asserts non-silent RMS, callable via audio.selfTest() and run it in eval.` },
  { key: 'hud', files: 'src/ui/HUD.js, src/ui/ui.css and new files under src/ui/', brief: `PIECE: HUD / UI. Own: src/ui/HUD.js, src/ui/ui.css, src/ui/*.js. Implement the header contract fully with a real art direction: FF14 ornate (thin gold filigree borders, soft aether-blue glows, serif-ish display font from the system stack e.g. 'Cinzel'-like feel via Georgia/Palatino small-caps, subtle gradient panels) + Destiny clarity/layout (crosshair center with archetype-specific reticle + spread + hit marker + crit/kill flash; bottom-right ammo mag/reserve big numerals + weapon name + element icon + 3 slot indicator; bottom-left 4 ability icons with radial cooldown sweep + ready pulse + super meter bar; top-left health + shield bars with regen shimmer and damage flash; damage numbers floating from world points (project with game.camera, pooled DOM, crit = bigger yellow, element colors); directional damage arcs around the crosshair; enemy nameplate/health bar for the target under the crosshair (raycast via game.combat.nearest/targets in a cone) with name + level + shield; boss bar top with phase ticks; toasts/notify banner (center, big, fades) and quest tracker (right); interaction prompt; pickup feed; low-health red vignette pulse (CSS); death screen + 'press any key to respawn' (call game.player.respawn at spawn); pause menu on ESC when not pointer-locked with sensitivity/fov/quality sliders wired to game.player.view.sensitivity/baseFov and location q param; start screen (keep click-to-begin + pointer lock); perf overlay toggle (F3, or ?debug=1 default on). Zero layout thrash: transforms + will-change, update text only when values change. Verify: screenshots of spawn (full HUD), firing (hit marker via combat events if dummy exists — use eval to emit events 'combat:hit' synthetic with point in front of camera to show damage numbers), damaged state (eval game.player.damage(40)), death screen, pause menu (eval to open).` },
]

const buildPrompt = (p, round, critic, prevReport) => `${COMMON}
${p.brief}
Files you own: ${p.files}. Do not edit anything else.
${critic ? `A fresh harsh critic inspected the running game and said (JSON): ${JSON.stringify(critic)}.
Fix the biggest gap FIRST, then the rest of gaps_ranked. Verify each fix in screenshots/perf before claiming it.` : ''}
${round === 0 ? 'The file is still a STUB (a previous builder was cut off before writing anything). Build the whole piece.' : 'NOTE: your files were already implemented by a previous builder (possibly cut off mid-work, possibly complete). Read them fully first, keep what is good, finish what is missing, then address the critic.'}
${prevReport ? `Previous builder report: ${prevReport}` : ''}
Return your report as plain text (<= 25 lines).`
const criticPrompt = (p, n) => `Project: C:\\Users\\ianca\\Desktop\\FPS3. Read tools/CRITIC.md in full and follow it exactly; also read CLAUDE.md. You are critic #${n} for PIECE "${p.key}" (files: ${p.files}). Piece brief (what the builder was asked to deliver): ${p.brief}
Inspect the actual running game with tools/inspect.mjs (use --name critic-${p.key}-${n}), look at the screenshots, read report.json, then do the blind side-by-side against the real Destiny 2 / FF14 equivalent and return the JSON verdict. Be brutal and specific.`

const MAX_FIX_ROUNDS = 3
const STUBS = new Set(['hud'])
const results = await pipeline(PIECES, async (p) => {
  const history = []
  let report = null, critic = null
  if (STUBS.has(p.key)) report = await agent(buildPrompt(p, 0, null, null), { label: `build:${p.key}#0`, phase: 'Build' })
  for (let round = 1; round <= MAX_FIX_ROUNDS + 1; round++) {
    critic = await agent(criticPrompt(p, round), { label: `critic:${p.key}#${round}`, phase: 'Critique', schema: CRITIC_SCHEMA })
    history.push({ round, report: (report || '').slice(0, 1500), critic })
    log(`${p.key} critic ${round}: ${critic?.verdict} ${critic?.score} — ${critic?.biggest_gap}`)
    if (!critic || critic.verdict === 'WIN' || round > MAX_FIX_ROUNDS) break
    report = await agent(buildPrompt(p, round, critic, report), { label: `build:${p.key}#${round}`, phase: 'Fix' })
  }
  return { piece: p.key, final: critic, history }
})
return results.filter(Boolean)